version: "3"
services:
  laravel:
    build: .
    ports:
    - "${NGINX_PORT}:80"
    - "${MYSQL_PORT}:3306"
    - "${SUPERVISOR_PORT}:9001"
    volumes:
    - ../:/var/www
    - /root
    - /var/lib/mysql
    - /var/log
